from node:lts-alpine 

workdir /authentication-server

copy package.json /authentication-server/package.json

run npm install
run npm install nodemon -g

run apk add --update nss-tools
run apk add --update curl
run apk add --update sed

run export ARCH=$(arch) \ 
&& if [ "${ARCH}" == "aarch64" ]; then \
    export ARCH="arm64"; \
    elif [ "${ARCH}" == "x86_64" ]; then \
    export ARCH="amd64"; fi \
&& echo $ARCH \
&& echo "https://dl.filippo.io/mkcert/latest?for=linux/${ARCH}" \
&& curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/${ARCH}" \
&& chmod +x mkcert-v*-linux-${ARCH} \
&& cp mkcert-v*-linux-${ARCH} /usr/local/bin/mkcert

run mkcert -install
