name: Client Unit-Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        node-versions: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Node Install
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: cd .\client\ ; npm i

      - name: Run Jest Unit-Tests
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: cd .\client\ ; npm run test_ci